/* This file is generated by hand, since the shell script will
 * not run under OS/2.
 */	
#ifndef _G_config_h
#define _G_config_h
#define _G_NAMES_HAVE_UNDERSCORE 1
#define _G_DOLLAR_IN_LABEL 1
#define _G_HAVE_ST_BLKSIZE 0
#define _G_clock_t long
#define _G_dev_t short
#define _G_fpos_t long
#define _G_gid_t int
#define _G_ino_t unsigned short
#define _G_mode_t unsigned short
#define _G_nlink_t short
#define _G_off_t long
#define _G_pid_t int
#define _G_ptrdiff_t long
#define _G_size_t unsigned long
#define _G_time_t long
#define _G_uid_t int
#define _G_wchar_t long
#define _G_ssize_t long
#define _G_NEED_STDARG_H
#define _G_va_list char*
#define _G_signal_return_type void
#define _G_sprintf_return_type int
#define _G_BUFSIZ  5120
#define _G_FOPEN_MAX 40
#define _G_FILENAME_MAX 260
#define _G_NULL 0
#define _G_ARGS(ARGLIST) ARGLIST
#define _G_SYSV
#define _G_HAVE_SYS_RESOURCE 0
#define _G_HAVE_SYS_SOCKET 0
#define _G_HAVE_UNISTD 1
#define _G_HAVE_DIRENT 1
#define _G_BROKEN_SIGNED_CHAR
#define _G_FRIEND_BUG
#endif /* !_G_config_h */
